packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  electron-winstaller: true
  esbuild: true
  node-pty: true
  protobufjs: true
  sharp: true
enableGlobalVirtualStore: true
packageExtensions:
  ink-testing-library:
    peerDependencies:
      ink: "*"
      react: "*"
