import {
  Activity,
  AlarmClock,
  AppWindow,
  Atom,
  Award,
  BarChart3,
  Bell,
  Blocks,
  BookOpen,
  Bot,
  Brain,
  Briefcase,
  Calculator,
  Calendar,
  Camera,
  Clock3,
  Cloud,
  Code2,
  Coffee,
  Compass,
  Cpu,
  Database,
  DollarSign,
  Dumbbell,
  FileText,
  Film,
  FlaskConical,
  Folder,
  Gamepad2,
  Globe,
  Heart,
  Image,
  Keyboard,
  LayoutDashboard,
  Lightbulb,
  Lock,
  Map as MapIcon,
  MessagesSquare,
  Music,
  Package,
  Palette,
  PenLine,
  Piano,
  Plane,
  Puzzle,
  Rocket,
  Settings2,
  Shield,
  ShoppingCart,
  Sparkles,
  Star,
  StickyNote,
  Sun,
  Terminal,
  Wallet,
  Wrench,
  Zap,
} from "lucide-react";
import type { ComponentType } from "react";

type DesktopIconComponent = ComponentType<{ className?: string }>;

/**
 * Icon keys external plugins may reference by string in `plugin.json` and in
 * their contributions. External plugin code cannot import lucide-react, so the
 * host resolves these keys before registering contributions. Unknown keys fall
 * back to the default plugin icon.
 */
const iconRegistry: Record<string, DesktopIconComponent> = {
  activity: Activity,
  "alarm-clock": AlarmClock,
  "app-window": AppWindow,
  atom: Atom,
  award: Award,
  "bar-chart": BarChart3,
  bell: Bell,
  blocks: Blocks,
  "book-open": BookOpen,
  bot: Bot,
  brain: Brain,
  briefcase: Briefcase,
  calculator: Calculator,
  calendar: Calendar,
  camera: Camera,
  clock: Clock3,
  cloud: Cloud,
  code: Code2,
  coffee: Coffee,
  compass: Compass,
  cpu: Cpu,
  database: Database,
  "dollar-sign": DollarSign,
  dumbbell: Dumbbell,
  "file-text": FileText,
  film: Film,
  "flask-conical": FlaskConical,
  folder: Folder,
  "gamepad-2": Gamepad2,
  globe: Globe,
  heart: Heart,
  image: Image,
  keyboard: Keyboard,
  "layout-dashboard": LayoutDashboard,
  lightbulb: Lightbulb,
  lock: Lock,
  map: MapIcon,
  messages: MessagesSquare,
  music: Music,
  package: Package,
  palette: Palette,
  "pen-line": PenLine,
  piano: Piano,
  plane: Plane,
  puzzle: Puzzle,
  rocket: Rocket,
  settings: Settings2,
  shield: Shield,
  "shopping-cart": ShoppingCart,
  sparkles: Sparkles,
  star: Star,
  "sticky-note": StickyNote,
  sun: Sun,
  terminal: Terminal,
  wallet: Wallet,
  wrench: Wrench,
  zap: Zap,
};

export const DEFAULT_PLUGIN_ICON = Blocks;

export function resolveDesktopIcon(spec: unknown): DesktopIconComponent {
  if (typeof spec === "function") return spec as DesktopIconComponent;
  if (typeof spec === "string") {
    const icon = iconRegistry[spec];
    if (icon) return icon;
  }
  return DEFAULT_PLUGIN_ICON;
}
