export type {
  AnyWorkspaceTabContribution,
  BuiltinWorkspaceTabType,
  ChatComposerToolContribution,
  ChatComposerToolProps,
  ChatContributionScope,
  ChatHeaderActionContribution,
  DesktopActionContribution,
  DesktopActionScope,
  DesktopIcon,
  DesktopPluginContext,
  DesktopPluginHandle,
  DesktopPluginInstallResult,
  DesktopPluginManifest,
  DesktopPluginModule,
  DesktopRouteContribution,
  DesktopShellContribution,
  DesktopShellScope,
  DesktopShortcut,
  DesktopUiSlot,
  SettingsPageContribution,
  SidebarNavigationContribution,
  WorkspaceTab,
  WorkspaceTabContribution,
  WorkspaceTabData,
  WorkspaceTabDataMap,
  WorkspaceTabRenderProps,
  WorkspaceTabScope,
  WorkspaceTabType,
} from "@chatdesk/desktop-plugin-sdk";
export { DESKTOP_PLUGIN_API_VERSION, defineDesktopPlugin } from "@chatdesk/desktop-plugin-sdk";
export type {
  ChatLayout,
  ChatLayoutComponent,
  ChatLayoutContribution,
  ChatLayoutProps,
  ChatLayoutScope,
} from "@/lib/chat-layout";
export { ChatLayoutService } from "@/lib/chat-layout";
export { DesktopUiService } from "@/lib/desktop-ui";
